# Generated by Django 2.2.5 on 2019-09-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0002_user'),
    ]

    operations = [
    ]
